name: Publish Package

on:
  release:
    types: [created]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04  # Explicitly using 22.04 for stability
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dillip285'
      
      # Install dependencies using clean install
      - name: Install dependencies using clean install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Run tests
      - name: Run tests
        run: npm test
      
      # Build the project
      - name: Build
        run: npm run build
      
      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}